#!/bin/sh

set -euo pipefail

usage() {
    echo "$0 [-l|-c] NUMBER"
    echo "read nth line/column from stdout"
}

badline() {
    case "$@" in
        '') true ;;
        [!0-9]*) true ;;
        *) test $@ -eq 0 ;;
    esac
}

case "$1" in
    -h|--help)
        usage
        ;;
    -l|--line)
        if badline ${2:-}; then usage >&2; exit 1; fi
        exec sed "$2q;d" <&0
        ;;
    -c|--column)
        if badline ${2:-}; then usage >&2; exit 1; fi
        exec awk "{ print \$$2 }" <&0
        ;;
    *)
        usage >&2
        exit 1
    ;;
esac
